include: package:strict_analyzer/analysis_options.yaml

analyzer:
  exclude:
    - lib/src/**.gr.dart
    - lib/**.gr.dart
    - lib/**.freezed.dart
    - lib/**.g.dart
  errors:
    unused_import: error
